import { LanguageCode, LanguagePack } from '../types';

export const LANGUAGE_METADATA: Record<
  LanguageCode,
  { name: string; nativeName: string; region: string }
> = {
  en: { name: 'English', nativeName: 'English', region: 'All India / Global' },
  as: { name: 'Assamese', nativeName: 'অসমীয়া', region: 'Assam & Brahmaputra Valley' },
  hi: { name: 'Hindi', nativeName: 'हिन्दी', region: 'National / Pan-NER' },
  mni: { name: 'Manipuri', nativeName: 'মৈতৈলোন্ / Manipuri', region: 'Manipur & Imphal Valley' },
};

const TRANSLATIONS: Record<LanguageCode, Record<string, string>> = {
  en: {
    // Brand & App Identity
    app_name: 'CognitiveSaathi',
    app_subtitle: 'Culturally Rooted Elder Care & Dementia Support',
    header_companion_btn: 'Companion',
    header_contrast_btn: 'Contrast',
    portal_caregiver: 'Care Circle',
    portal_patient: 'Companion',
    btn_switch_to_caregiver: 'Caregiver',
    btn_switch_to_patient: 'Patient View',
    btn_signout: 'Log out',
    select_language: 'Select Language',
    status_live: 'Live',
    status_syncing: 'Syncing',
    status_offline: 'Offline',

    // Navigation
    nav_home: 'Home',
    nav_games: 'Games',
    nav_my_day: 'My Day',
    nav_memories: 'Memories',
    nav_me: 'Profile',
    nav_comfort: 'Comfort',
    nav_overview: 'Overview',
    nav_routines: 'Routines',
    nav_meds: 'Meds',
    nav_clinical_ai: 'Clinical AI',
    nav_circle: 'Care Circle',

    // Home Screen
    welcome_back: 'Welcome home,',
    calm_reassurance: 'You are safe, loved, and peacefully resting with family.',
    start_daily_exercise: 'Start Today’s Keepsake Activity',
    voice_companion: 'Talk to Saathi Companion',
    caregiver_portal: 'Family & Caregiver Portal',
    emergency_call: 'Call My Family Caregiver',
    daily_streak: 'Day Daily Streak',
    completed_today: 'activities completed today',
    listen_prompt: 'Tap to listen to peaceful audio guidance',
    today_routine: 'My Day & Peaceful Routines',
    see_all_routines: 'See all routines',
    no_routines_today: 'No routines scheduled for today.',
    family_memories: 'Heritage & Photo Reminiscence',
    view_memory_album: 'View memory album',
    no_memories_yet: 'No memories added to the album yet.',
    care_circle_title: 'Your Family Care Circle is Here',
    care_circle_subtitle: 'Always connected with love, care, and continuous support.',
    call_btn: 'Call',

    // Activities & Games
    activities_title: 'Cognitive Activities & Keepsake Games',
    activities_subtitle: 'Calm, scientifically designed cognitive exercises tailored for memory stimulation and joy.',
    filter_all: 'All Activities',
    game_memory_tiles_title: 'Memory Tiles (Card Matching)',
    game_memory_tiles_desc: 'Flip and match serene cultural and nature cards to gently stimulate visual memory.',
    game_memory_tiles_btn: 'Play Memory Tiles',
    game_recognize_desc_title: 'Recognize Objects by Description',
    game_recognize_desc_desc: 'Read or listen to gentle descriptions and discover the right item.',
    game_recognize_desc_btn: 'Play Object Discovery',
    game_personal_quiz_title: 'Personal Memories & Loved Ones Quiz',
    game_personal_quiz_desc: 'Answer gentle 4-choice questions about your family members, loved ones, and life scenarios generated directly by AI from your personal memories.',
    game_personal_quiz_btn: 'Play Memory Quiz',
    game_personal_quiz_awaiting: 'Awaiting Memories & Loved Ones',
    game_personal_quiz_blank: 'Add moments or loved ones in the Memories tab to unlock your personal quiz!',
    game_personal_quiz_unlock: 'Add in Memories Tab',
    game_matching_title: 'Find Matching Pairs',
    game_matching_desc: 'A simple, visual matching exercise with cheerful everyday items.',
    game_matching_btn: 'Play Matching Game',
    game_pattern_title: 'Music Pattern Sequence',
    game_pattern_desc: 'Listen to melodious Indian instruments and follow the soothing sequence.',
    game_pattern_btn: 'Play Music Pattern',
    game_story_recall_title: 'Story Recall & Familiarity',
    game_story_recall_desc: 'Enjoy a short heritage narrative and reminisce about familiar traditions.',
    game_story_recall_btn: 'Play Story Recall',

    // My Day Screen
    my_day_title: 'My Day & Gentle Schedule',
    my_day_subtitle: 'Peaceful, step-by-step daily routines and medication reminders.',
    routines_section_title: 'Today’s Schedule & Routines',
    routine_add_new: 'Add New Routine',
    status_completed: 'Completed',
    status_pending: 'Pending',
    btn_mark_done: 'Mark Done',
    btn_undo: 'Undo',
    reminders_section_title: 'Medication & Health Reminders',
    reminder_add_new: 'Add Reminder',
    reminder_taken: 'Taken',
    reminder_mark_taken: 'Mark as Taken',
    reminder_no_items: 'No medication reminders for today.',

    // Memories Screen
    memories_title: 'Cherished Family & Cultural Memories',
    memories_subtitle: 'Cherished family photos, life stories, and loved ones in your life.',
    tab_photo_album: 'Photo Album & Stories',
    tab_loved_ones: 'Loved Ones in My Life',
    btn_record_voice_story: 'Record Voice Story',
    btn_add_memory: 'Add New Memory',
    btn_listen_story: 'Listen to Story',
    memories_empty_title: 'No memories added to the album yet',
    memories_empty_desc: 'Preserve precious moments by tapping "Add New Memory" or recording a voice keepsake.',
    loved_ones_title: 'People in My Life',
    btn_add_loved_one: 'Add Loved One',
    loved_ones_empty_title: 'No loved ones added yet',
    loved_ones_empty_desc: 'Add family members, children, or friends to build a comforting circle of familiar faces.',
    label_relationship: 'Relationship',

    // Me / Profile Screen
    me_title: 'My Profile & Safe Contacts',
    me_subtitle: 'Personal care profile, safe emergency contacts, and care circle.',
    personal_info_title: 'Personal Information',
    label_full_name: 'Full Name',
    label_preferred_name: 'Preferred Name',
    label_age: 'Age',
    label_cultural_region: 'Cultural Region',
    label_primary_language: 'Primary Language',
    label_medical_notes: 'Medical Notes & Comfort Preferences',
    caregiver_info_title: 'Primary Family Caregiver',
    label_caregiver_name: 'Caregiver Name',
    label_caregiver_phone: 'Caregiver Phone',
    btn_edit_profile: 'Edit Profile',
    btn_save_profile: 'Save Profile Changes',

    // Settings / Comfort Screen
    settings_title: 'Accessibility & Display Comfort',
    settings_subtitle: 'Adjust text size, contrast, and language for maximum visual comfort.',
    high_contrast: 'High Contrast Display',
    high_contrast_desc: 'Enhances borders, text darkness, and sharp edges for easy viewing.',
    large_text: 'Enlarged Text for Ease',
    large_text_desc: 'Increases text size throughout the app for effortless reading.',
    language_section_title: 'Choose App & Audio Language',
    language_section_desc: 'All text, buttons, and Saathi AI voice companion will seamlessly speak and adapt to this language.',
    audio_settings_title: 'Audio & Gentle Sound Effects',
    audio_settings_desc: 'Plays gentle chimes and comforting sound cues during activities.',
    sync_section_title: 'Data & Offline Care Protection',
    sync_section_desc: 'All patient memories, schedules, and scores are preserved offline and synced securely.',
    sync_status_connected: 'Securely Connected',
    sync_status_offline: 'Offline Care Mode Active',
    sync_now_btn: 'Test Reconnect & Sync Telemetry',

    // Voice Companion Modal
    companion_title: 'Companion',
    companion_thinking: 'Thinking',
    companion_subtitle: 'Grounded in your real schedule, routines & memories',
    companion_voice_on: 'Voice On',
    companion_muted: 'Muted',
    companion_input_placeholder: 'Speak gently or type in any language...',
    companion_listening: 'Listening to your voice...',
    companion_transcribing: 'Understanding your speech...',
    companion_tap_to_speak: 'Tap to Speak',
    companion_stop_send: 'Stop & Send',
    companion_cancel: 'Cancel',
    companion_starters_title: 'Gentle Conversation Starters',
    companion_thought_process: 'Cognitive Reasoning & Grounding',
    companion_error_no_speech: 'I could not hear any spoken words. Please tap the microphone and speak gently, or choose a prompt below.',
    companion_p_schedule: '📅 What is my schedule like?',
    companion_p_next: '🚶 What is my next activity?',
    companion_p_memories: '📸 Has memories tab updated?',
    companion_p_medicine: '💊 Did I take my medicine?',
    companion_p_caregiver: '👵 Who is looking after me?',
    companion_p_story: '🌸 Tell me a peaceful story',
    companion_q_schedule: 'What is my schedule like today?',
    companion_q_next: 'What is my next activity?',
    companion_q_memories: 'Has the memories tab been updated recently?',
    companion_q_medicine: 'Did I take my medicine today?',
    companion_q_caregiver: 'Who is looking after me today?',
    companion_q_story: 'Tell me a peaceful short story about Assam tea gardens and morning birds',

    // Common
    close: 'Close',
    save: 'Save',
    cancel: 'Cancel',
  },
  as: {
    // Brand & App Identity
    app_name: 'সাথী',
    app_subtitle: 'সাংস্কৃতিকভাৱে শিপাই থকা জ্যেষ্ঠ সেৱা আৰু স্মৃতি সহায়ক',
    header_companion_btn: 'সাথী',
    header_contrast_btn: 'কণ্ট্ৰাষ্ট',
    portal_caregiver: 'সেৱা চক্ৰ',
    portal_patient: 'সংগী',
    btn_switch_to_caregiver: 'সেৱক',
    btn_switch_to_patient: 'জ্যেষ্ঠ মোড',
    btn_signout: 'লগ আউট',
    select_language: 'ভাষা বাছক',
    status_live: 'লাইভ',
    status_syncing: 'সংযোগ হৈছে',
    status_offline: 'অফলাইন',

    // Navigation
    nav_home: 'ঘৰ',
    nav_games: 'খেলা',
    nav_my_day: 'মোৰ দিন',
    nav_memories: 'স্মৃতি',
    nav_me: 'পৰিচয়',
    nav_comfort: 'সুবিধা',
    nav_overview: 'অৱলোকন',
    nav_routines: 'ৰুটিন',
    nav_meds: 'ঔষধ',
    nav_clinical_ai: 'ক্লিনিকেল AI',
    nav_circle: 'সেৱা চক্ৰ',

    // Home Screen
    welcome_back: 'ঘৰলৈ স্বাগতম,',
    calm_reassurance: 'আপুনি ঘৰত সম্পূৰ্ণ সুৰক্ষিত, মৰমত আৰু শান্তিত আছে।',
    start_daily_exercise: 'আজিৰ স্মৃতি খেলা আৰম্ভ কৰক',
    voice_companion: 'সাথীৰ লগত কথা পাতক',
    caregiver_portal: 'পৰিয়াল আৰু সেৱক প’ৰ্টেল',
    emergency_call: 'পৰিয়ালৰ লগত কথা পাতক',
    daily_streak: 'দিনৰ ধাৰাবাহিকতা',
    completed_today: 'টা কাম আজি সম্পূৰ্ণ হৈছে',
    listen_prompt: 'শান্তিপূৰ্ণ নিৰ্দেশনা শুনিবলৈ স্পৰ্শ কৰক',
    today_routine: 'মোৰ দিন আৰু শান্তিপূৰ্ণ কাম-কাজ',
    see_all_routines: 'সকলো ৰুটিন চাওক',
    no_routines_today: 'আজিৰ বাবে কোনো কাম বাকী নাই।',
    family_memories: 'পৰম্পৰা আৰু পুৰণি স্মৃতি',
    view_memory_album: 'স্মৃতি এলবাম চাওক',
    no_memories_yet: 'এতিয়ালৈকে কোনো স্মৃতি যোগ কৰা হোৱা নাই।',
    care_circle_title: 'আপোনাৰ পৰিয়াল আপোনাৰ কাষতেই আছে',
    care_circle_subtitle: 'সদায় মৰম আৰু সুৰক্ষাৰে সংযোগ হৈ আছে।',
    call_btn: 'কল কৰক',

    // Activities & Games
    activities_title: 'মগজুৰ খেলা আৰু স্মৃতি চৰ্চা',
    activities_subtitle: 'স্মৃতি সজীৱ আৰু মন শান্ত ৰাখিবলৈ বৈজ্ঞানিকভাৱে নিৰ্মিত খেলা।',
    filter_all: 'সকলো খেলা',
    game_memory_tiles_title: 'স্মৃতি কাৰ্ড মিলোৱা (Memory Tiles)',
    game_memory_tiles_desc: 'ছবিবোৰ লুটিয়াই একে কাৰ্ডবোৰ মিলাওক আৰু স্মৃতি সতেজ কৰক।',
    game_memory_tiles_btn: 'কাৰ্ড খেলা আৰম্ভ কৰক',
    game_recognize_desc_title: 'বিৱৰণ চাই বস্তু চিনাক্ত কৰক',
    game_recognize_desc_desc: 'বিৱৰণ শুনি বা পঢ়ি সঠিক বস্তুটো বাছি উলিয়াওক।',
    game_recognize_desc_btn: 'চিনাক্ত খেলা আৰম্ভ কৰক',
    game_personal_quiz_title: 'ব্যক্তিগত স্মৃতি আৰু আপোনজনৰ কুইজ',
    game_personal_quiz_desc: 'আপোনাৰ পৰিয়াল, আপোনজন আৰু জীৱনৰ সোঁৱৰণিৰ ওপৰত সহজ প্ৰশ্নোত্তৰ।',
    game_personal_quiz_btn: 'স্মৃতি কুইজ আৰম্ভ কৰক',
    game_personal_quiz_awaiting: 'স্মৃতি আৰু আপোনজনৰ তথ্য প্ৰয়োজন',
    game_personal_quiz_blank: 'আপোনাৰ কুইজ আৰম্ভ কৰিবলৈ স্মৃতি টেবত ফটো বা পৰিয়ালৰ সদস্য যোগ কৰক!',
    game_personal_quiz_unlock: 'স্মৃতি টেবত যোগ কৰক',
    game_matching_title: 'যোৰ মিলোৱা খেল',
    game_matching_desc: 'দৈনন্দিন বস্তুৰ সহজ আৰু আনন্দদায়ক মিলোৱা খেলা।',
    game_matching_btn: 'মিলন খেল আৰম্ভ কৰক',
    game_pattern_title: 'সুৰ আৰু ছন্দৰ অনুশীলন',
    game_pattern_desc: 'শান্তিপূৰ্ণ বাদ্যযন্ত্ৰৰ ধ্বনি শুনি ছন্দ অনুসৰণ কৰক।',
    game_pattern_btn: 'সুৰৰ খেলা আৰম্ভ কৰক',
    game_story_recall_title: 'সাধু আৰু পৰম্পৰাৰ সোঁৱৰণি',
    game_story_recall_desc: 'চেনেহীয়া সাধু শুনি পুৰণি ঐতিহ্য মনত পেলাওক।',
    game_story_recall_btn: 'সাধু শুনা আৰম্ভ কৰক',

    // My Day Screen
    my_day_title: 'মোৰ দিন আৰু দৈনন্দিন নিয়ম',
    my_day_subtitle: 'শান্তিপূৰ্ণভাৱে দৈনন্দিন কাম আৰু ঔষধৰ তালিকা অনুসৰণ কৰক।',
    routines_section_title: 'আজিৰ কাম আৰু ৰুটিন',
    routine_add_new: 'নতুন ৰুটিন যোগ কৰক',
    status_completed: 'সম্পূৰ্ণ হ’ল',
    status_pending: 'বাকী আছে',
    btn_mark_done: 'সম্পূৰ্ণ কৰা হ’ল',
    btn_undo: 'পূৰ্বৰ অৱস্থালৈ নিয়ক',
    reminders_section_title: 'ঔষধ আৰু স্বাস্থ্য সোঁৱৰণি',
    reminder_add_new: 'নতুন ঔষধ যোগ কৰক',
    reminder_taken: 'খোৱা হ’ল',
    reminder_mark_taken: 'ঔষধ খোৱা হ’ল',
    reminder_no_items: 'আজিৰ বাবে কোনো ঔষধ বাকী নাই।',

    // Memories Screen
    memories_title: 'মৰমৰ পৰিয়াল আৰু সাংস্কৃতিক স্মৃতি',
    memories_subtitle: 'পুৰণি ফটো, জীৱনৰ কাহিনী আৰু মৰমৰ আপোন মানুহবোৰ।',
    tab_photo_album: 'ফটো এলবাম আৰু কাহিনী',
    tab_loved_ones: 'মোৰ জীৱনৰ আপোনজন',
    btn_record_voice_story: 'কণ্ঠৰে স্মৃতি ৰেকৰ্ড কৰক',
    btn_add_memory: 'নতুন স্মৃতি যোগ কৰক',
    btn_listen_story: 'কাহিনী শুনক',
    memories_empty_title: 'এতিয়ালৈকে কোনো স্মৃতি যোগ কৰা হোৱা নাই',
    memories_empty_desc: 'নতুন স্মৃতি যোগ কৰিবলৈ ওপৰৰ বুটামত স্পৰ্শ কৰক।',
    loved_ones_title: 'মোৰ জীৱনৰ আপোন মানুহ',
    btn_add_loved_one: 'আপোনজনক যোগ কৰক',
    loved_ones_empty_title: 'এতিয়ালৈকে কোনো আপোনজন যোগ কৰা হোৱা নাই',
    loved_ones_empty_desc: 'পৰিয়ালৰ সদস্য বা বন্ধু-বান্ধৱী যোগ কৰক।',
    label_relationship: 'সম্পৰ্ক',

    // Me / Profile Screen
    me_title: 'মোৰ পৰিচয় আৰু সহায়কাৰী',
    me_subtitle: 'ব্যক্তিগত তথ্য, জৰুৰীকালীন যোগাযোগ আৰু সেৱা চক্ৰ।',
    personal_info_title: 'ব্যক্তিগত তথ্য',
    label_full_name: 'সম্পূৰ্ণ নাম',
    label_preferred_name: 'মতা নাম',
    label_age: 'বয়স',
    label_cultural_region: 'অঞ্চল আৰু সংস্কৃতি',
    label_primary_language: 'প্ৰধান ভাষা',
    label_medical_notes: 'স্বাস্থ্য আৰু বিশেষ সুবিধা',
    caregiver_info_title: 'প্ৰধান পৰিয়াল সেৱক',
    label_caregiver_name: 'সেৱকৰ নাম',
    label_caregiver_phone: 'ফোন নম্বৰ',
    btn_edit_profile: 'তথ্য সলনি কৰক',
    btn_save_profile: 'সংৰক্ষণ কৰক',

    // Settings / Comfort Screen
    settings_title: 'সহজ পঠন আৰু সুবিধা',
    settings_subtitle: 'চকুৰ সুবিধাৰ বাবে আখৰৰ আকাৰ, ৰং আৰু ভাষা নিৰ্বাচন কৰক।',
    high_contrast: 'স্পষ্ট আৰু ডাঠ ৰং (High Contrast)',
    high_contrast_desc: 'পঢ়িবলৈ সহজ হ’বলৈ কাষৰ ৰেখা আৰু আখৰবোৰ ডাঠ কৰে।',
    large_text: 'ডাঙৰ আখৰ',
    large_text_desc: 'সহজে পঢ়িবলৈ সমগ্ৰ এপটোৰ আখৰৰ আকাৰ বৃদ্ধি কৰে।',
    language_section_title: 'এপ আৰু কণ্ঠৰ ভাষা নিৰ্বাচন কৰক',
    language_section_desc: 'এপৰ সকলো লেখা, বুটাম আৰু সাথী AI ভইচ সংগীয়ে এই ভাষাত কথা পাতিব।',
    audio_settings_title: 'শান্তিপূৰ্ণ ধ্বনি আৰু শব্দ',
    audio_settings_desc: 'খেলা আৰু কাম সম্পূৰ্ণ কৰোঁতে শান্ত সুৰ বজায়।',
    sync_section_title: 'তথ্য সুৰক্ষা আৰু অফলাইন মোড',
    sync_section_desc: 'ইণ্টাৰনেট নাথাকিলেও সকলো তথ্য সুৰক্ষিতভাৱে থাকে।',
    sync_status_connected: 'সুৰক্ষিতভাৱে সংযোগ আছে',
    sync_status_offline: 'অফলাইন মোড সক্ৰিয়',
    sync_now_btn: 'তথ্য পুনৰ সংলগ্ন কৰক',

    // Voice Companion Modal
    companion_title: 'সাথী সংগী',
    companion_thinking: 'চিন্তন',
    companion_subtitle: 'আপোনাৰ দৈনিক কাৰ্য্যসূচী, ৰুটিন আৰু স্মৃতিৰ সৈতে যুক্ত',
    companion_voice_on: 'কণ্ঠ অন',
    companion_muted: 'শব্দহীন',
    companion_input_placeholder: 'মৰমেৰে কথা কওক বা লিখক...',
    companion_listening: 'আপোনাৰ কথা শুনি আছোঁ...',
    companion_transcribing: 'কথা বুজিবলৈ চেষ্টা কৰিছোঁ...',
    companion_tap_to_speak: 'কথা ক’বলৈ স্পৰ্শ কৰক',
    companion_stop_send: 'পঠিয়াওক',
    companion_cancel: 'বাতিল',
    companion_starters_title: 'সহজ কথা-বতৰাৰ প্ৰশ্ন',
    companion_thought_process: 'চিন্তন প্ৰক্ৰিয়া আৰু তথ্য',
    companion_error_no_speech: 'মই কোনো শব্দ শুনি নাপালোঁ। অনুগ্ৰহ কৰি মাইক্ৰ’ফনত স্পৰ্শ কৰি কওক বা তলৰ প্ৰশ্ন এটা বাছক।',
    companion_p_schedule: '📅 মোৰ কাৰ্য্যসূচী কি?',
    companion_p_next: '🚶 মোৰ পৰৱৰ্তী কাম কি?',
    companion_p_memories: '📸 পুৰণি স্মৃতিসমূহ আছে নেকি?',
    companion_p_medicine: '💊 মই ঔষধ খালোঁনে?',
    companion_p_caregiver: '👵 মোৰ যত্ন কোনে লৈছে?',
    companion_p_story: '🌸 মোক এটা ধুনীয়া সাধু কওক',
    companion_q_schedule: 'আজি মোৰ দিনটোৰ কাৰ্য্যসূচী কি?',
    companion_q_next: 'মোৰ পৰৱৰ্তী কাৰ্য্য কি?',
    companion_q_memories: 'মোৰ সোঁৱৰণি (Memories) টেবটোত নতুন কিবা আছে নেকি?',
    companion_q_medicine: 'মই আজি ঔষধ খালোঁনে?',
    companion_q_caregiver: 'আজি মোৰ যত্ন কোনে লৈছে?',
    companion_q_story: 'মোক এখন অসমৰ ধুনীয়া চাহ বাগিচা আৰু চৰাইৰ সাধু শুনাওক',

    // Common
    close: 'বন্ধ কৰক',
    save: 'সংৰক্ষণ কৰক',
    cancel: 'বাতিল',
  },
  hi: {
    // Brand & App Identity
    app_name: 'साथी',
    app_subtitle: 'संस्कृति से जुड़ी बुजुर्ग देखभाल और स्मृति साथी',
    header_companion_btn: 'साथी',
    header_contrast_btn: 'कंट्रास्ट',
    portal_caregiver: 'देखभाल चक्र',
    portal_patient: 'साथी',
    btn_switch_to_caregiver: 'देखभालकर्ता',
    btn_switch_to_patient: 'मरीज मोड',
    btn_signout: 'लॉग आउट',
    select_language: 'भाषा चुनें',
    status_live: 'लाइव',
    status_syncing: 'सिंक हो रहा है',
    status_offline: 'ऑफ़लाइन',

    // Navigation
    nav_home: 'होम',
    nav_games: 'खेल',
    nav_my_day: 'दिनचर्या',
    nav_memories: 'यादें',
    nav_me: 'प्रोफ़ाइल',
    nav_comfort: 'सुविधा',
    nav_overview: 'विवरण',
    nav_routines: 'दिनचर्या',
    nav_meds: 'दवाएं',
    nav_clinical_ai: 'क्लिनिकल AI',
    nav_circle: 'देखभाल चक्र',

    // Home Screen
    welcome_back: 'स्वागत है,',
    calm_reassurance: 'आप घर पर बिल्कुल सुरक्षित हैं और आपका परिवार आपके साथ है।',
    start_daily_exercise: 'आज का स्मृति खेल शुरू करें',
    voice_companion: 'साथी से बात करें',
    caregiver_portal: 'देखभालकर्ता पोर्टल',
    emergency_call: 'देखभालकर्ता को कॉल करें',
    daily_streak: 'दिनों का क्रम',
    completed_today: 'कार्य आज पूरे हुए',
    listen_prompt: 'मार्गदर्शन सुनने के लिए टैप करें',
    today_routine: 'मेरी दिनचर्या और शांतिपूर्ण कार्य',
    see_all_routines: 'सभी दिनचर्या देखें',
    no_routines_today: 'आज के लिए कोई निर्धारित कार्य नहीं है।',
    family_memories: 'पारिवारिक और सांस्कृतिक यादें',
    view_memory_album: 'स्मृति एल्बम देखें',
    no_memories_yet: 'अभी तक कोई याद नहीं जोड़ी गई है।',
    care_circle_title: 'आपका परिवार आपके साथ है',
    care_circle_subtitle: 'सदा स्नेह और सुरक्षा के साथ जुड़े हुए हैं।',
    call_btn: 'कॉल करें',

    // Activities & Games
    activities_title: 'स्मृति अभ्यास और खेल',
    activities_subtitle: 'स्मृति और मानसिक शांति के लिए वैज्ञानिक रूप से तैयार खेल।',
    filter_all: 'सभी खेल',
    game_memory_tiles_title: 'मेमोरी कार्ड मिलान (Memory Tiles)',
    game_memory_tiles_desc: 'शांत सांस्कृतिक और प्राकृतिक चित्रों को मिलाएं और स्मृति को तेज करें।',
    game_memory_tiles_btn: 'कार्ड खेलें',
    game_recognize_desc_title: 'विवरण से वस्तु पहचानें',
    game_recognize_desc_desc: 'विवरण सुनकर या पढ़कर सही वस्तु पहचानें।',
    game_recognize_desc_btn: 'पहचान खेलें',
    game_personal_quiz_title: 'पारिवारिक यादें और प्रियजनों की पहेली',
    game_personal_quiz_desc: 'अपने परिवार, प्रियजनों और जीवन की यादों पर आधारित सरल प्रश्न।',
    game_personal_quiz_btn: 'स्मृति पहेली खेलें',
    game_personal_quiz_awaiting: 'यादों और प्रियजनों की प्रतीक्षा',
    game_personal_quiz_blank: 'यह खेल शुरू करने के लिए यादें टैब में परिवार या कोई याद जोड़ें!',
    game_personal_quiz_unlock: 'यादें टैब में जोड़ें',
    game_matching_title: 'जोड़े खोजें',
    game_matching_desc: 'दैनिक वस्तुओं का सरल और सुंदर मिलान अभ्यास।',
    game_matching_btn: 'मिलान खेलें',
    game_pattern_title: 'संगीत पैटर्न खेल',
    game_pattern_desc: 'मधुर भारतीय वाद्ययंत्रों की धुन सुनकर क्रम पहचानें।',
    game_pattern_btn: 'संगीत खेलें',
    game_story_recall_title: 'कहानी और परंपरा स्मरण',
    game_story_recall_desc: 'सुंदर लोक कथाओं को सुनकर अपनी परंपराओं को याद करें।',
    game_story_recall_btn: 'कहानी खेलें',

    // My Day Screen
    my_day_title: 'मेरी दिनचर्या और समय',
    my_day_subtitle: 'शांतिपूर्ण दैनिक कार्य और दवाओं का समय।',
    routines_section_title: 'आज की दिनचर्या और कार्य',
    routine_add_new: 'नई दिनचर्या जोड़ें',
    status_completed: 'पूर्ण',
    status_pending: 'शेष',
    btn_mark_done: 'पूरा हुआ',
    btn_undo: 'पूर्ववत करें',
    reminders_section_title: 'दवा और स्वास्थ्य अनुस्मारक',
    reminder_add_new: 'नई दवा जोड़ें',
    reminder_taken: 'ली गई',
    reminder_mark_taken: 'दवा ले ली',
    reminder_no_items: 'आज के लिए कोई दवा शेष नहीं है।',

    // Memories Screen
    memories_title: 'पारिवारिक और अनमोल यादें',
    memories_subtitle: 'परिवार की पुरानी तस्वीरें, जीवन की कहानियां और प्रियजन।',
    tab_photo_album: 'फोटो एल्बम और कहानियां',
    tab_loved_ones: 'मेरे प्रियजन',
    btn_record_voice_story: 'आवाज़ में कहानी रिकॉर्ड करें',
    btn_add_memory: 'नई याद जोड़ें',
    btn_listen_story: 'कहानी सुनें',
    memories_empty_title: 'अभी तक कोई याद नहीं जोड़ी गई है',
    memories_empty_desc: 'नई याद जोड़ने के लिए ऊपर दिए गए बटन पर टैप करें।',
    loved_ones_title: 'मेरे जीवन के प्रियजन',
    btn_add_loved_one: 'प्रियजन जोड़ें',
    loved_ones_empty_title: 'अभी तक कोई प्रियजन नहीं जोड़ा गया है',
    loved_ones_empty_desc: 'परिवार के सदस्यों और मित्रों को जोड़ें।',
    label_relationship: 'रिश्ता',

    // Me / Profile Screen
    me_title: 'मेरी प्रोफ़ाइल और संपर्क',
    me_subtitle: 'व्यक्तिगत जानकारी, आपातकालीन संपर्क और देखभाल चक्र।',
    personal_info_title: 'व्यक्तिगत विवरण',
    label_full_name: 'पूरा नाम',
    label_preferred_name: 'पुकार का नाम',
    label_age: 'आयु',
    label_cultural_region: 'क्षेत्र और संस्कृति',
    label_primary_language: 'प्राथमिक भाषा',
    label_medical_notes: 'स्वास्थ्य और आराम संबंधी बातें',
    caregiver_info_title: 'मुख्य देखभालकर्ता',
    label_caregiver_name: 'देखभालकर्ता का नाम',
    label_caregiver_phone: 'फ़ोन नंबर',
    btn_edit_profile: 'प्रोफ़ाइल बदलें',
    btn_save_profile: 'सहेजें',

    // Settings / Comfort Screen
    settings_title: 'पहुंच और सुविधा सेटिंग्स',
    settings_subtitle: 'आँखों के आराम के लिए अक्षर, कंट्रास्ट और भाषा चुनें।',
    high_contrast: 'उच्च कंट्रास्ट (High Contrast)',
    high_contrast_desc: 'स्पष्ट देखने के लिए अक्षरों और किनारों को गहरा करता है।',
    large_text: 'बड़े अक्षर',
    large_text_desc: 'आसानी से पढ़ने के लिए अक्षरों का आकार बड़ा करता है।',
    language_section_title: 'ऐप और आवाज़ की भाषा चुनें',
    language_section_desc: 'ऐप के सभी शब्द, बटन और साथी AI आवाज़ तुरंत इसी भाषा में बदल जाएंगे।',
    audio_settings_title: 'मधुर ध्वनि और संगीत',
    audio_settings_desc: 'गतिविधियों के दौरान मधुर और शांत स्वर बजाता है।',
    sync_section_title: 'डेटा और ऑफ़लाइन सुरक्षा',
    sync_section_desc: 'इंटरनेट न होने पर भी सभी डेटा सुरक्षित रहता है।',
    sync_status_connected: 'सुरक्षित रूप से जुड़ा हुआ',
    sync_status_offline: 'ऑफ़लाइन मोड सक्रिय',
    sync_now_btn: 'सिंक की जांच करें',

    // Voice Companion Modal
    companion_title: 'साथी',
    companion_thinking: 'चिंतन',
    companion_subtitle: 'आपकी वास्तविक दिनचर्या और यादों से जुड़ा हुआ',
    companion_voice_on: 'आवाज़ चालू',
    companion_muted: 'मौन',
    companion_input_placeholder: 'प्यार से बोलें या किसी भी भाषा में लिखें...',
    companion_listening: 'आपकी बात सुन रहा हूँ...',
    companion_transcribing: 'आपकी आवाज़ समझ रहा हूँ...',
    companion_tap_to_speak: 'बोलने के लिए टैप करें',
    companion_stop_send: 'भेजें',
    companion_cancel: 'रद्द करें',
    companion_starters_title: 'बातचीत की शुरुआत के लिए प्रश्न',
    companion_thought_process: 'विचार प्रक्रिया और संदर्भ',
    companion_error_no_speech: 'मुझे कोई आवाज़ सुनाई नहीं दी। कृपया माइक टैप करके प्यार से बोलें या नीचे से कोई प्रश्न चुनें।',
    companion_p_schedule: '📅 मेरी दिनचर्या क्या है?',
    companion_p_next: '🚶 मेरी अगली गतिविधि क्या है?',
    companion_p_memories: '📸 क्या यादें अपडेट हुई हैं?',
    companion_p_medicine: '💊 क्या मैंने आज दवा ली?',
    companion_p_caregiver: '👵 मेरी देखभाल कौन कर रहा है?',
    companion_p_story: '🌸 मुझे एक शांतिपूर्ण कहानी सुनाएं',
    companion_q_schedule: 'आज मेरी दिनचर्या क्या है?',
    companion_q_next: 'मेरी अगली गतिविधि क्या है?',
    companion_q_memories: 'क्या मेरी यादें (Memories) हाल ही में अपडेट हुई हैं?',
    companion_q_medicine: 'क्या मैंने आज की दवा समय पर ली?',
    companion_q_caregiver: 'आज मेरी देखभाल कौन कर रहा है?',
    companion_q_story: 'मुझे असम के चाय बागानों और सुबह की सुंदर चिड़ियों की एक शांत कहानी सुनाएं',

    // Common
    close: 'बंद करें',
    save: 'सहेजें',
    cancel: 'रद्द करें',
  },
  mni: {
    // Brand & App Identity
    app_name: 'সাথী',
    app_subtitle: 'লমদমগী নাৎকা শম্নবা নুংশিরবা কেয়ার অমসুং মেমোরি সাথী',
    header_companion_btn: 'সাথী',
    header_contrast_btn: 'মচু',
    portal_caregiver: 'কেয়ার সার্কেল',
    portal_patient: 'সাথী',
    btn_switch_to_caregiver: 'কেয়ারগিভার',
    btn_switch_to_patient: 'পেসেন্ট মোড',
    btn_signout: 'লোগ আউৎ',
    select_language: 'লোন খনবিয়ু',
    status_live: 'লাইভ',
    status_syncing: 'সিঙ্ক তৌরি',
    status_offline: 'অফলাইন',

    // Navigation
    nav_home: 'য়ুম',
    nav_games: 'শান্নপোৎ',
    nav_my_day: 'ঐগী নুমিৎ',
    nav_memories: 'নিংশিংপোৎ',
    nav_me: 'মশক',
    nav_comfort: 'সেটিং',
    nav_overview: 'য়েন্থোকপা',
    nav_routines: 'রুটিন',
    nav_meds: 'হিদাক',
    nav_clinical_ai: 'ক্লিনিকেল AI',
    nav_circle: 'কেয়ার সার্কেল',

    // Home Screen
    welcome_back: 'খুরুমজরি,',
    calm_reassurance: 'অদোম য়ুমদা শান্তিনা অমসুং নিংথিনা লৈরি।',
    start_daily_exercise: 'ঙসিগী ৱাখলগী শান্নপোৎ হৌসি',
    voice_companion: 'সাথীগা ৱারী শানসি',
    caregiver_portal: 'ইমুংগী কেয়ারগিভার পোর্টেল',
    emergency_call: 'কেয়ারগিভারদা কোল তৌবা',
    daily_streak: 'নুমিৎগী লেপ্পা লৈতবা খোঙচৎ',
    completed_today: 'থবক ঙসি লোইশিনখ্রে',
    listen_prompt: 'নুংশিবা ঈশৈ অমসুং নিংশিংবা তারসি',
    today_routine: 'ঐগী নুমিৎ অমসুং রুটিন',
    see_all_routines: 'রুটিন পুম্নমক য়েংবা',
    no_routines_today: 'ঙসিগী ওইনা অমত্তা লেপ্ত্রি।',
    family_memories: 'ইমুং-মনুংগী নিংশিংপোৎ',
    view_memory_album: 'এলবাম য়েংবা',
    no_memories_yet: 'হৌজিকফাওবা অমত্তা হাপ্পা লৈত্ৰি।',
    care_circle_title: 'অদোমগী ইমুং অদোমগী নক্ননা লৈ',
    care_circle_subtitle: 'নুংশিবা অমসুং ঙাক-শেনগা লোয়ননা লৈরি।',
    call_btn: 'কোল তৌবা',

    // Activities & Games
    activities_title: 'ৱাখল শান্নপোৎ অমসুং মেমোরি গেম',
    activities_subtitle: 'ৱাখল নুংঙাইহনবা অমসুং নিংশিংবা হেনগৎহনবা শান্নপোৎ।',
    filter_all: 'শান্নপোৎ পুম্নমক',
    game_memory_tiles_title: 'মেমোরি কার্দ মেচিং (Memory Tiles)',
    game_memory_tiles_desc: 'ফোতোগা ফোতোগা য়েন্থোকুনা মান্নবা কার্দশিং পুন্সিনসি।',
    game_memory_tiles_btn: 'কার্দ শানসি',
    game_recognize_desc_title: 'মরোল তারগা পোৎ শকখঙবা',
    game_recognize_desc_desc: 'ৱাফম তারগা অচুম্বা পোৎশক খনবিয়ু।',
    game_recognize_desc_btn: 'পোৎশক খঙবা শানসি',
    game_personal_quiz_title: 'ইমুং-মনুং অমসুং নিংশিং কুইজ',
    game_personal_quiz_desc: 'ইমুংগী মীশিং অমসুং নিংশিংপোৎকী মতাংদা খংদোকপা।',
    game_personal_quiz_btn: 'মেমোরি কুইজ শানসি',
    game_personal_quiz_awaiting: 'নিংশিংপোৎ অমসুং মী হাপ্পা ঙাইরি',
    game_personal_quiz_blank: 'কুইজ অসি হাংদোক্নবা মেমোরিজ তেবতা ইমুংগী মী নত্রগা নিংশিংপোৎ হাপ্পিয়ু!',
    game_personal_quiz_unlock: 'মেমোরিজ তেবতা হাপ্পা',
    game_matching_title: 'মান্নবা যোর থিবা',
    game_matching_desc: 'নোংমগী পোৎশকশিং মান্নবা মচাক থিবা।',
    game_matching_btn: 'যোর শানসি',
    game_pattern_title: 'ঈশৈগী মখল মেচিং',
    game_pattern_desc: 'নুংশিরবা খুৎঈশৈ তারগা মতুং ইনসি।',
    game_pattern_btn: 'ঈশৈ শানসি',
    game_story_recall_title: 'ৱারী নিংশিংবা',
    game_story_recall_desc: 'অরিবা ৱারী তারগা নিংশিংসি।',
    game_story_recall_btn: 'ৱারী শানসি',

    // My Day Screen
    my_day_title: 'ঐগী নুমিৎ অমসুং রুটিন',
    my_day_subtitle: 'অকক্নবা মতমগী রুটিন অমসুং হিদাক্কী নিংশিংবা।',
    routines_section_title: 'ঙসিগী রুটিন',
    routine_add_new: 'অনৌবা রুটিন হাপ্পা',
    status_completed: 'লোইরে',
    status_pending: 'ৱাত্লি',
    btn_mark_done: 'লোইরে খঙহনবা',
    btn_undo: 'হান্নবা মতৌ',
    reminders_section_title: 'হিদাক অমসুং হকশেলগী নিংশিংবা',
    reminder_add_new: 'অনৌবা হিদাক হাপ্পা',
    reminder_taken: 'চাখ্রে',
    reminder_mark_taken: 'হিদাক চাখ্রে',
    reminder_no_items: 'ঙসিগী ওইনা হিদাক অমত্তা ৱাত্ৰে।',

    // Memories Screen
    memories_title: 'নিংথিরবা নিংশিং খুদমশিং',
    memories_subtitle: 'ইমুংগী ফোতো, পুন্সিগী ৱারী অমসুং নুংশিরবা মীশিং।',
    tab_photo_album: 'ফোতো এলবাম অমসুং ৱারী',
    tab_loved_ones: 'ঐগী পুন্সিগী মীশিং',
    btn_record_voice_story: 'খোঞ্জেলদা ৱারী রেকোর্দ তৌবা',
    btn_add_memory: 'অনৌবা নিংশিংপোৎ হাপ্পা',
    btn_listen_story: 'ৱারী তাবা',
    memories_empty_title: 'হৌজিকফাওবা নিংশিংপোৎ অমত্তা হাপ্পা লৈত্ৰি',
    memories_empty_desc: 'অনৌবা নিংশিংপোৎ হাপ্নবা মথক্কী বতনদা নম্বিয়ু।',
    loved_ones_title: 'ঐগী নুংশিরবা মীশিং',
    btn_add_loved_one: 'অনৌবা মী হাপ্পা',
    loved_ones_empty_title: 'হৌজিকফাওবা মী অমত্তা হাপ্পা লৈত্ৰি',
    loved_ones_empty_desc: 'ইমুংগী মী অমসুং মরুপ-মপাং হাপ্পিয়ু।',
    label_relationship: 'মরী',

    // Me / Profile Screen
    me_title: 'ঐগী মশক অমসুং কন্টাক্ট',
    me_subtitle: 'ঐগী অকক্নবা মশক অমসুং ইমুংগী পাউ।',
    personal_info_title: 'ঐগী অকক্নবা মরম',
    label_full_name: 'মপুং ফাবা মিং',
    label_preferred_name: 'কৌবা মিং',
    label_age: 'চহি',
    label_cultural_region: 'লমদম অমসুং নাৎ',
    label_primary_language: 'মরুওইবা লোন',
    label_medical_notes: 'হকশেল অমসুং নুংঙাইবা মতৌ',
    caregiver_info_title: 'মরুওইবা কেয়ারগিভার',
    label_caregiver_name: 'কেয়ারগিভারগী মিং',
    label_caregiver_phone: 'ফোন নম্বর',
    btn_edit_profile: 'মশক শেমদোকপা',
    btn_save_profile: 'সেভ তৌবা',

    // Settings / Comfort Screen
    settings_title: 'সুবিধা অমসুং সেটিং',
    settings_subtitle: 'মীত নুংঙাইহন্নবা ময়েক চাউথোকপা অমসুং লোন খনবিয়ু।',
    high_contrast: 'ময়েক শেংবা মচুগী স্ক্রিন',
    high_contrast_desc: 'য়েংবা নুংঙাইনবা ময়েক অমসুং কাংখাক শেংহনবা।',
    large_text: 'চাউবা ময়েক',
    large_text_desc: 'লাইনা পাবা য়ানবা ময়েক্কী চাউবা হেনগৎহনবা।',
    language_section_title: 'এপ অমসুং খোঞ্জেলগী লোন খনবিয়ু',
    language_section_desc: 'এপকী ৱাহৈ, বতন অমসুং সাথী AI খোঞ্জেল পুম্নমক মসিগী লোনদা ওন্থোক্কনি।',
    audio_settings_title: 'নুংশিরবা খোঞ্জেল অমসুং ঈশৈ',
    audio_settings_desc: 'শান্নপোৎ মতমদা তোপ তোপ লাওবা খোঞ্জেল তারসি।',
    sync_section_title: 'দেতা অমসুং অফলাইন ঙাক-শেন',
    sync_section_desc: 'ইন্তর্নেত লৈতবসু দেতা পুম্নমক অফলাইনদা লৈরি।',
    sync_status_connected: 'কনেক্ট তৌদুনা লৈরে',
    sync_status_offline: 'অফলাইন মোড চত্থরি',
    sync_now_btn: 'হৌজিক সিঙ্ক তৌবা',

    // Voice Companion Modal
    companion_title: 'সাথী',
    companion_thinking: 'ৱাখল তৌরি',
    companion_subtitle: 'অদোমগী রুটিন অমসুং নিংশিংপোৎকা শম্নবা',
    companion_voice_on: 'খোঞ্জেল য়াওরি',
    companion_muted: 'খোঞ্জেল য়াওদে',
    companion_input_placeholder: 'তপ্না ৱারী শানবিয়ু নত্রগা ইবিয়ু...',
    companion_listening: 'অদোমগী খোঞ্জেল তারি...',
    companion_transcribing: 'খোঞ্জেল খঙবা ঙম্নবা হোৎনরি...',
    companion_tap_to_speak: 'ঙাংনবগীদমক নম্বিয়ু',
    companion_stop_send: 'থাবা',
    companion_cancel: 'তোখায়বা',
    companion_starters_title: 'ৱারী হৌদোক্নবা ৱাহং',
    companion_thought_process: 'ৱাখলগী মরম',
    companion_error_no_speech: 'ঐহাক্না ৱাফম অমত্তা তাদে। মাইক্রোফোন নম্বিয়ু নত্রগা মখাগী ৱাহং খনবিয়ু।',
    companion_p_schedule: '📅 ঐগী রুটিন করম্না লৈরি?',
    companion_p_next: '🚶 ঐগী মথংগী থবক করি?',
    companion_p_memories: '📸 নিংশিংপোৎকী খোমজিনবা মতম?',
    companion_p_medicine: '💊 ঙসি হিদাক চাবা য়ারব্রা?',
    companion_p_caregiver: '👵 ঐবু কনানা য়েংশিনবিরি?',
    companion_p_story: '🌸 নুংশিরবা ৱারী অমা তারসি',
    companion_q_schedule: 'ঙসি ঐগী রুটিন করি করি লৈবগে?',
    companion_q_next: 'ঐগী মথংদা তৌগদবা থবক করি?',
    companion_q_memories: 'মেমোরিজ তেবতা অনৌবা নিংশিংপোৎ হাপ্লব্রা?',
    companion_q_medicine: 'ঙসিগী হিদাক চাবা লোইরব্ৰা?',
    companion_q_caregiver: 'ঙসি ঐবু কনানা য়েংশিনবিরিগে?',
    companion_q_story: 'অসামগী চা বাগান অমসুং উচেশিংগী মতাংদা নুংশিরবা ৱারী অমা তাকপিয়ু',

    // Common
    close: 'থিংশিনবা',
    save: 'সেভ তৌবা',
    cancel: 'তোখায়বা',
  },
};

export const DEFAULT_LANGUAGE_PACKS: LanguagePack[] = [
  {
    language_code: 'en',
    language_name: 'English',
    translations: TRANSLATIONS.en,
    audio_assets: {},
    version: '1.2.0',
    validation_status: 'approved',
    download_status: 'downloaded',
    isPilot: false,
  },
  {
    language_code: 'as',
    language_name: 'অসমীয়া (Assamese)',
    translations: TRANSLATIONS.as,
    audio_assets: {},
    version: '1.2.0',
    validation_status: 'approved',
    download_status: 'downloaded',
    isPilot: true,
  },
  {
    language_code: 'hi',
    language_name: 'हिन्दी (Hindi)',
    translations: TRANSLATIONS.hi,
    audio_assets: {},
    version: '1.2.0',
    validation_status: 'approved',
    download_status: 'downloaded',
    isPilot: false,
  },
  {
    language_code: 'mni',
    language_name: 'মৈতৈলোন্ (Manipuri)',
    translations: TRANSLATIONS.mni,
    audio_assets: {},
    version: '1.0.0',
    validation_status: 'reviewed',
    download_status: 'downloaded',
    isPilot: true,
  },
];

export function getTranslation(key: string, lang: LanguageCode = 'en'): string {
  if (TRANSLATIONS[lang] && TRANSLATIONS[lang][key]) {
    return TRANSLATIONS[lang][key];
  }
  return TRANSLATIONS.en[key] || key;
}
